In [1]:
%load_ext autoreload
%autoreload 2
%cd 'python/AggNet/'
%ls

/home/hew/python/AggNet
data/  framework/  main.py  script/  temp/


In [43]:
import biotite.structure as struc

from framework import paths
from framework.utils.bio.struct_utils import get_atom_array, atom_array_to_sequence, compute_adjacency_matrix, \
    compute_distance_matrix, construct_graph, get_neighbors, compute_sasa
from framework.utils.file.read_utils import read_fasta

paths

{'path_dataset': '/home/hew/python/data/', 'root': '/home/hew/python/AggNet/', 'data': '/home/hew/python/AggNet/data/', 'script': '/home/hew/python/AggNet/script/', 'temp': '/home/hew/python/AggNet/temp/', 'framework': '/home/hew/python/AggNet/framework/', 'config': '/home/hew/python/AggNet/framework/config/', 'module': '/home/hew/python/AggNet/framework/module/', 'utils': '/home/hew/python/AggNet/framework/utils/'}

In [3]:
pdb_path = paths.data + '/ProteinDataBank/pdb/102L.pdb'
fasta_path = paths.data + '/ProteinDataBank/fasta/102L.fasta'

## load pdb files as the atom array

In [4]:
atom_array = get_atom_array(pdb_path, clean=True)
atom_array

array([
	Atom(np.array([44.061, -3.277,  8.755], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="N", element="N"),
	Atom(np.array([43.619, -1.924,  8.869], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([42.195, -1.991,  9.394], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="C", element="C"),
	Atom(np.array([41.523, -2.983,  9.193], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="O", element="O"),
	Atom(np.array([43.727, -1.353,  7.458], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CB", element="C"),
	Atom(np.array([42.994, -0.069,  7.291], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CG", element="C"),
	Atom(np.array([44.005,  1.333,  7.794], dtype=float32), chain_id="A", 

In [5]:
atom_array[-5:]

array([
	Atom(np.array([48.399, -0.233,  2.395], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="CB", element="C"),
	Atom(np.array([47.487, -0.828,  3.442], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="CG", element="C"),
	Atom(np.array([47.042, -2.267,  3.144], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="CD", element="C"),
	Atom(np.array([47.048, -2.611,  1.653], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="CE", element="C"),
	Atom(np.array([45.951, -3.517,  1.236], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="NZ", element="N")
])

In [6]:
ids, names = struc.get_residues(atom_array)
ids, names

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162]),
 array(['MET', 'ASN', 'ILE', 'PHE', 'GLU', 'MET', 'LEU', 'ARG', 'ILE',
        

## convert atom array to sequence and compare to the fasta sequence

In [7]:
sequences, descriptions = read_fasta(fasta_path)
sequences, descriptions

(['MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL'],
 ['102L_1|Chain A|T4 LYSOZYME|Enterobacteria phage T4 (10665)'])

In [8]:
convert_seq = atom_array_to_sequence(atom_array)
convert_seq, len(convert_seq)

('MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYK',
 163)

In [9]:
sequences[0], len(sequences[0])

('MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL',
 165)

In [10]:
for i in range(len(list(sequences[0]))):
    if i >= len(convert_seq):
        print(i, sequences[0][i], 'None')
    else:
        if sequences[0][i] == convert_seq[i]:
            pass
        else:
            print(i, sequences[0][i], convert_seq[i])

163 N None
164 L None


## compute adjacency and distance matrices

In [25]:
adjacency_matrix = compute_adjacency_matrix(atom_array, threshold=8)
adjacency_matrix

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

In [26]:
distance_matrix = compute_distance_matrix(atom_array)
distance_matrix

array([[ 0.       ,  3.7968643,  7.186744 , ..., 11.063123 ,  8.376107 ,
         8.632469 ],
       [ 3.7968643,  0.       ,  3.8486917, ..., 12.795138 , 10.350898 ,
        11.6755295],
       [ 7.186744 ,  3.8486917,  0.       , ..., 13.356713 , 11.17711  ,
        13.497336 ],
       ...,
       [11.063123 , 12.795138 , 13.356713 , ...,  0.       ,  3.6950703,
         5.7112155],
       [ 8.376107 , 10.350898 , 11.17711  , ...,  3.6950703,  0.       ,
         3.7632942],
       [ 8.632469 , 11.6755295, 13.497336 , ...,  5.7112155,  3.7632942,
         0.       ]], dtype=float32)

In [27]:
adjacency_matrix_2 = distance_matrix < 8
adjacency_matrix_2

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

In [28]:
(adjacency_matrix_2 == adjacency_matrix).all()

True

In [48]:
nodes, edges = construct_graph(atom_array)
nodes.shape, edges.shape

((163,), (163, 163))

In [49]:
nodes

array(['M', 'N', 'I', 'F', 'E', 'M', 'L', 'R', 'I', 'D', 'E', 'G', 'L',
       'R', 'L', 'K', 'I', 'Y', 'K', 'D', 'T', 'E', 'G', 'Y', 'Y', 'T',
       'I', 'G', 'I', 'G', 'H', 'L', 'L', 'T', 'K', 'S', 'P', 'S', 'L',
       'N', 'A', 'A', 'A', 'K', 'S', 'E', 'L', 'D', 'K', 'A', 'I', 'G',
       'R', 'N', 'T', 'N', 'G', 'V', 'I', 'T', 'K', 'D', 'E', 'A', 'E',
       'K', 'L', 'F', 'N', 'Q', 'D', 'V', 'D', 'A', 'A', 'V', 'R', 'G',
       'I', 'L', 'R', 'N', 'A', 'K', 'L', 'K', 'P', 'V', 'Y', 'D', 'S',
       'L', 'D', 'A', 'V', 'R', 'R', 'A', 'A', 'L', 'I', 'N', 'M', 'V',
       'F', 'Q', 'M', 'G', 'E', 'T', 'G', 'V', 'A', 'G', 'F', 'T', 'N',
       'S', 'L', 'R', 'M', 'L', 'Q', 'Q', 'K', 'R', 'W', 'D', 'E', 'A',
       'A', 'V', 'N', 'L', 'A', 'K', 'S', 'R', 'W', 'Y', 'N', 'Q', 'T',
       'P', 'N', 'R', 'A', 'K', 'R', 'V', 'I', 'T', 'T', 'F', 'R', 'T',
       'G', 'T', 'W', 'D', 'A', 'Y', 'K'], dtype='<U1')

In [50]:
edges

array([[ 0.       ,  3.7968643,  7.186744 , ..., 11.063123 ,  8.376107 ,
         8.632469 ],
       [ 3.7968643,  0.       ,  3.8486917, ..., 12.795138 , 10.350898 ,
        11.6755295],
       [ 7.186744 ,  3.8486917,  0.       , ..., 13.356713 , 11.17711  ,
        13.497336 ],
       ...,
       [11.063123 , 12.795138 , 13.356713 , ...,  0.       ,  3.6950703,
         5.7112155],
       [ 8.376107 , 10.350898 , 11.17711  , ...,  3.6950703,  0.       ,
         3.7632942],
       [ 8.632469 , 11.6755295, 13.497336 , ...,  5.7112155,  3.7632942,
         0.       ]], dtype=float32)

## find neighbors

In [15]:
atom_array[0].coord

array([44.061, -3.277,  8.755], dtype=float32)

In [16]:
atom_indices, near_atoms, residue_indices, near_residue_atoms, near_residue_c_atoms = get_neighbors(atom_array[0].coord,
                                                                                                    atom_array,
                                                                                                    cell_list=None,
                                                                                                    cell_size=5,
                                                                                                    radius=8.0,
                                                                                                    near_residues=True)
near_atoms

array([
	Atom(np.array([40.172, -1.685,  5.852], dtype=float32), chain_id="A", res_id=158, ins_code="", res_name="TRP", hetero=False, atom_name="CE2", element="C"),
	Atom(np.array([39.211, -1.241,  6.746], dtype=float32), chain_id="A", res_id=158, ins_code="", res_name="TRP", hetero=False, atom_name="CZ2", element="C"),
	Atom(np.array([40.325, -1.552, 12.05 ], dtype=float32), chain_id="A", res_id=2, ins_code="", res_name="ASN", hetero=False, atom_name="CB", element="C"),
	Atom(np.array([39.855,  0.989,  6.078], dtype=float32), chain_id="A", res_id=158, ins_code="", res_name="TRP", hetero=False, atom_name="CZ3", element="C"),
	Atom(np.array([40.049,  0.598, 10.743], dtype=float32), chain_id="A", res_id=2, ins_code="", res_name="ASN", hetero=False, atom_name="C", element="C"),
	Atom(np.array([38.797,  0.867, 11.127], dtype=float32), chain_id="A", res_id=3, ins_code="", res_name="ILE", hetero=False, atom_name="N", element="N"),
	Atom(np.array([39.069,  0.103,  6.843], dtype=float32), chai

In [17]:
near_residue_atoms

array([
	Atom(np.array([44.061, -3.277,  8.755], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="N", element="N"),
	Atom(np.array([43.619, -1.924,  8.869], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([42.195, -1.991,  9.394], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="C", element="C"),
	Atom(np.array([41.523, -2.983,  9.193], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="O", element="O"),
	Atom(np.array([43.727, -1.353,  7.458], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CB", element="C"),
	Atom(np.array([42.994, -0.069,  7.291], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CG", element="C"),
	Atom(np.array([44.005,  1.333,  7.794], dtype=float32), chain_id="A", 

In [18]:
near_residue_c_atoms

array([
	Atom(np.array([43.619, -1.924,  8.869], dtype=float32), chain_id="A", res_id=1, ins_code="", res_name="MET", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([40.445, -0.876, 10.67 ], dtype=float32), chain_id="A", res_id=2, ins_code="", res_name="ASN", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([38.254,  2.24 , 11.22 ], dtype=float32), chain_id="A", res_id=3, ins_code="", res_name="ILE", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([48.558,  1.279,  2.555], dtype=float32), chain_id="A", res_id=162, ins_code="", res_name="LYS", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([43.586,  3.293, 12.11 ], dtype=float32), chain_id="A", res_id=5, ins_code="", res_name="GLU", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([41.968,  4.686,  9.048], dtype=float32), chain_id="A", res_id=6, ins_code="", res_name="MET", hetero=False, atom_name="CA", element="C"),
	Atom(np.array([42.337, -0.615,  1.978], dtype=float32), chain_id=

## compute SASA

In [23]:
residue_sasa = compute_sasa(atom_array)
residue_sasa

array([7.84750137e+01, 6.88024445e+01, 2.57511253e+01, 8.02616730e+01,
       8.98170319e+01, 0.00000000e+00, 0.00000000e+00, 9.85082855e+01,
       8.98112030e+01, 2.10858212e+01, 4.24474525e+01, 2.38149834e+01,
       4.15973320e+01, 1.31611603e+02, 6.86500473e+01, 9.71112366e+01,
       1.78761139e+01, 2.93134422e+01, 1.25811432e+02, 4.41842575e+01,
       1.13452538e+02, 7.35726852e+01, 3.62349663e+01, 6.77773743e+01,
       2.60628452e+01, 3.58542681e+00, 0.00000000e+00, 9.99328047e-02,
       4.44112110e+00, 1.75586071e+01, 3.34624939e+01, 7.28793488e+01,
       1.66886215e+01, 2.12527962e+01, 1.38961578e+02, 4.15398216e+01,
       1.29321564e+02, 5.24118042e+01, 6.09033470e+01, 1.02903931e+02,
       6.18292923e+01, 2.94723015e+01, 0.00000000e+00, 3.27536049e+01,
       6.36896248e+01, 5.63076630e+01, 0.00000000e+00, 3.22520714e+01,
       1.45383286e+02, 4.65494194e+01, 3.58469849e+01, 6.53495941e+01,
       9.72711334e+01, 1.36064606e+02, 9.53537560e+00, 1.13500534e+02,
      

In [24]:
residue_sasa.shape

(163,)